import type { CrmStore } from '../crm.types';

export type CrmSequenceRepository = Pick<
  CrmStore,
  | 'countOwnerQueuedMessages'
  | 'countDispatchedMessages'
  | 'listOwnerSendStates'
  | 'listMailboxSendStates'
  | 'listDueSendCandidates'
  | 'listStaleQueuedMessages'
  | 'findActiveEnrollmentByContact'
  | 'findActiveEnrollmentByAccount'
  | 'createSequenceEnrollment'
  | 'createSequenceDraftBundle'
  | 'createFollowUpDraftBundle'
  | 'listSequenceReviewItems'
  | 'getSequenceReviewItem'
  | 'listSequenceReviewItemsByIds'
  | 'updateSequenceEnrollment'
  | 'createMessage'
  | 'findMessageById'
  | 'findSentMessageByProviderId'
  | 'findSentMessageByProviderThreadId'
  | 'updateMessage'
  | 'createMessageDraftVersion'
  | 'listMessageDraftVersions'
  | 'restoreMessageDraftVersion'
  | 'approveMessageDraft'
  | 'startFirstMessageSend'
  | 'claimFirstMessageSendDelivery'
  | 'stopSequenceEnrollment'
  | 'completeFirstMessageSend'
  | 'failFirstMessageSend'
  | 'createAiDraftTask'
  | 'countActiveAiDraftTasksForUser'
  | 'countActiveAiDraftTasksForOrg'
  | 'findCurrentAiDraftTaskForUser'
  | 'findAiDraftTaskById'
  | 'listAiDraftTasks'
  | 'listAiDraftTaskItems'
  | 'updateAiDraftTask'
  | 'updateAiDraftTaskItem'
>;
