export const AI_LEAD_KEYWORD_HISTORY_STORE = Symbol('AI_LEAD_KEYWORD_HISTORY_STORE');
export const AI_LEAD_SEARCH_TASK_STORE = Symbol('AI_LEAD_SEARCH_TASK_STORE');
export const AI_LEAD_QUEUE_CONFIG_STORE = Symbol('AI_LEAD_QUEUE_CONFIG_STORE');
export const AI_LEAD_DIRECTORY_SOURCE_RULE_STORE = Symbol('AI_LEAD_DIRECTORY_SOURCE_RULE_STORE');
export const AI_LEAD_SEARCH_TASK_QUEUE = Symbol('AI_LEAD_SEARCH_TASK_QUEUE');
