/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ai-leads',
    path: '/ai-leads',
    component: 'layout.base$view.ai-leads',
    meta: {
      title: 'ai-leads',
      i18nKey: 'route.ai-leads',
      icon: 'mdi:account-search-outline',
      order: 2
    }
  },
  {
    name: 'ai-prompt-settings',
    path: '/ai-prompt-settings',
    component: 'layout.base$view.ai-prompt-settings',
    meta: {
      title: 'ai-prompt-settings',
      i18nKey: 'route.ai-prompt-settings',
      icon: 'mdi:file-document-edit-outline',
      order: 4,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'ai-settings',
    path: '/ai-settings',
    component: 'layout.base$view.ai-settings',
    meta: {
      title: 'ai-settings',
      i18nKey: 'route.ai-settings',
      icon: 'mdi:server-network-outline',
      order: 3,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 6,
      roles: ['R_SUPER']
    },
    children: [
      {
        name: 'manage_system-log',
        path: '/manage/system-log',
        component: 'view.manage_system-log',
        meta: {
          title: 'manage_system-log',
          i18nKey: 'route.manage_system-log',
          icon: 'mdi:clipboard-text-clock-outline',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_SUPER']
        }
      }
    ]
  }
];
