import type { CrmStore } from '../crm.types';

export type CrmSettingsRepository = Pick<
  CrmStore,
  | 'getGlobalConfig'
  | 'saveGlobalConfig'
  | 'getSendPreference'
  | 'saveSendPreference'
  | 'getOrganizationConfig'
  | 'saveOrganizationConfig'
  | 'listProductLines'
  | 'findProductLineByName'
  | 'findProductLineById'
  | 'createProductLine'
  | 'updateProductLine'
  | 'createProductLineAiPromptVersion'
  | 'listProductLineAiPromptVersions'
  | 'restoreProductLineAiPromptVersion'
  | 'listPersonaProfiles'
  | 'listActivePersonaProfiles'
  | 'findPersonaProfileByName'
  | 'findPersonaProfileById'
  | 'createPersonaProfile'
  | 'updatePersonaProfile'
  | 'setDefaultPersonaProfile'
  | 'listEmailTemplateGroups'
  | 'findEmailTemplateGroupByName'
  | 'findEmailTemplateGroupById'
  | 'findDefaultEmailTemplateGroup'
  | 'createEmailTemplateGroup'
  | 'updateEmailTemplateGroup'
  | 'setDefaultEmailTemplateGroup'
  | 'listSequencePolicies'
  | 'findSequencePolicyByName'
  | 'findSequencePolicyById'
  | 'findDefaultSequencePolicy'
  | 'createSequencePolicy'
  | 'updateSequencePolicy'
  | 'setDefaultSequencePolicy'
  | 'getAiDraftQueueConfig'
  | 'saveAiDraftQueueConfig'
>;
